platform :ios, '13.2'

source 'https://cdn.cocoapods.org/'

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'ImageFlip' do
  pod 'Alloy/Shaders'
  pod 'SnapKit'
  pod 'PHAssetPicker', '1.0.2'
  pod 'MetalView', '1.0.0'
  pod 'SwiftGen'
end
