platform :ios, '13.2'

source 'https://cdn.cocoapods.org/'

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

def pods
  pod 'Alloy/Shaders'
  pod 'SnapKit'
  pod 'PHAssetPicker'
  pod 'MetalView'
  pod 'SwiftGen'
end

target 'ImageFlip' do
  pods
end

target 'ImageFlipUITests' do
  pods
  pod 'SwiftSnapshotTesting', :path => '~/github/eugenebokhan/SwiftSnapshotTesting'
end
